package saritnike:cipher@0.1.0;

interface audit-log {
    auditrecord: func(action: string, detail: string);
}

world encoder-decoder-service {

    import audit-log;

    // had to change name to avoid conflict with encrypt function in libc.so
    // see: https://github.com/bytecodealliance/componentize-py/issues/187
    export encr: func(input: string) -> string;
    export decr: func(input: string) -> string;

    
}